# -*- coding: utf-8 -*-
"""Copy of AI Nurse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yheCQLUxh4oWuN0qmOmw2s7_mJoMJpnT
"""

import nltk
from nltk.chat.util import Chat, reflections

# Example pairs for the chatbot
pairs = [
    [
        r"hi|hello|hey",
        ["Hello! How can I assist you today?", "Hi there! What can I help you with?"]
    ],
    [
        r"thank you|thanks",
        ["You're welcome!", "Anytime! I'm here to help."]
    ],
    [
        r"i am not feeling well|i am not feeling so well today",
        ["I am sorry to hear about that. Could you please tell me more?"]
    ],
    [
        r"(.*) headache(.*)",
        ["For a headache, try resting in a quiet room and stay hydrated. If it persists, consult a healthcare professional."]
    ],
    # Add more pairs as needed
]

# Create a chatbot instance
chatbot = Chat(pairs, reflections)

# Start the chatbot
def start_chat():
    print("DPS AI Nurse: Hi, I'm here to help with your health concerns! Type 'quit' to exit.")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("DPS AI Nurse: Take care! See you soon.")
            break
        response = chatbot.respond(user_input)
        print("DPS AI Nurse:", response)

# Start the chatbot
start_chat()

!pip install nltk

!pip install streamlit

import nltk
from nltk.chat.util import Chat, reflections

# Define a more extensive set of pairs to cover various situations
pairs = [
    [
        r"hi|hello|hey",
        ["Hello! How can I assist you today?", "Hi there! What can I help you with?"]
    ],
    [
        r"thank you|thanks",
        ["You're welcome! If you need anything else, I'm here.", "Anytime! Stay healthy!"]
    ],
    [
        r"i am not feeling well|i am not feeling so well today",
        ["I'm sorry to hear that. Can you tell me more about how you're feeling?", "I hope it's nothing serious. Please describe your symptoms."]
    ],
    [
        r"(.*) headache(.*)",
        ["For a headache, try resting in a quiet, dark room and drinking plenty of water. If it persists, inform a teacher or visit the school nurse."]
    ],
    [
        r"(.*) stomachache|stomach pain(.*)",
        ["For a stomachache, consider sipping on some water, and avoid eating heavy food. If the pain continues, it might be best to rest and see the nurse."]
    ],
    [
        r"(.*) stress|anxious(.*)",
        ["Stress is common, especially during exams. Try some deep breathing exercises and take a few moments to relax. If it continues, talk to a counselor or trusted teacher."]
    ],
    [
        r"(.*) depression(.*)",
        ["I'm really sorry you're feeling this way. It's important to talk to someone who can help, like a counselor or a trusted adult. Remember, you're not alone."]
    ],
    [
        r"(.*) anxiety(.*)",
        ["Anxiety can be tough. Try focusing on your breathing and grounding exercises like naming things you can see, hear, and feel. If it gets overwhelming, talk to someone who can support you."]
    ],
    [
        r"(.*) mensural cramps(.*)",
        ["For menstrual cramps, resting with a warm compress can help. Staying hydrated and avoiding caffeine might also ease the discomfort. If it’s severe, visit the school nurse."]
    ],
    [
        r"(.*) sprain(.*)",
        ["If you’ve sprained something, elevate the area, apply ice, and try not to move it too much. Get help from a teacher or the nurse for proper care."]
    ],
    [
        r"(.*) cuts|wound(.*)",
        ["For minor cuts, wash the area with clean water, apply a bandage, and keep it clean. If it's deep or doesn't stop bleeding, seek help from the nurse immediately."]
    ],
    [
        r"(.*) hygiene(.*)",
        ["Good hygiene is key to staying healthy. Remember to wash your hands regularly, especially before eating and after using the restroom."]
    ],
    [
        r"(.*) nutrition(.*)",
        ["Eating a balanced diet is important. Make sure to include fruits, vegetables, and proteins in your meals. Drink plenty of water to stay hydrated."]
    ],
    [
        r"(.*) fever(.*)",
        ["If you're feeling feverish, it's important to rest and drink plenty of fluids. Inform your teacher, and they may send you to the nurse to check your temperature."]
    ],
    [
        r"(.*) dizzy|dizziness(.*)",
        ["If you're feeling dizzy, sit down and rest for a moment. Drink some water and breathe slowly. If it continues, visit the school nurse."]
    ],
    [
        r"(.*) diarrhea(.*)",
        ["Diarrhea can be uncomfortable. Stay hydrated by sipping water, and avoid eating anything that might upset your stomach further. Let a teacher know so you can get the right care."]
    ],
    [
        r"(.*) cold|flu(.*)",
        ["If you’re showing symptoms of a cold or flu, like a runny nose or cough, rest as much as you can. Drink warm fluids and stay hydrated. If symptoms worsen, visit the nurse."]
    ],
    [
        r"(.*) asthma(.*)",
        ["If you're having an asthma attack, use your inhaler immediately. If you don’t have it with you, go to the nurse or tell a teacher right away."]
    ],
    [
        r"(.*) faint(.*)",
        ["If you feel like you might faint, sit or lie down immediately. Raise your legs if possible and take deep breaths. Tell a teacher or student to get help."]
    ],
    [
        r"(.*) allergies(.*)",
        ["If you're having an allergic reaction, inform a teacher or the nurse immediately. If you have an EpiPen, use it as directed."]
    ]
]

# Create a chatbot instance with reflections
chatbot = Chat(pairs, reflections)

# Function to start the chatbot
def start_chat():
    print("DPS AI Nurse: Hello! I'm here to help with your health concerns. Type 'quit' to exit.")
    while True:
        user_input = input("You: ").lower()
        if user_input == 'quit':
            print("DPS AI Nurse: Take care! See you soon.")
            break
        response = chatbot.respond(user_input)
        print("DPS AI Nurse:", response)

# Start the chatbot
start_chat()

# Save this code as 'dps_ai_nurse.py'
import streamlit as st
from nltk.chat.util import Chat, reflections

# Define your chatbot pairs and reflections as before
pairs = [
    [
        r"hi|hello|hey",
        ["Hello! How can I assist you today?", "Hi there! What can I help you with?"]
    ],
    # Add the rest of your chatbot responses here...
]

# Create the Chat object
chatbot = Chat(pairs, reflections)

# Streamlit code to create the interface
st.title("DPS AI Nurse")
st.write("Hello! I'm here to help with your health concerns. How can I assist you today?")

# User input
user_input = st.text_input("You:", "Type here...")

if user_input:
    response = chatbot.respond(user_input.lower())
    st.text_area("DPS AI Nurse:", value=response, height=100)

!streamlit run dps_ai_nurse.py